### ISSUE TITLE
No admin route

### ISSUE THREAD

**Issue by sedubois** [lazaronixon/administration-zero#1]
Thanks for this new gem! I generated an app as follows:
```rb
rails new --javascript=esbuild demoapp && cd demoapp
rails generate model post title:string body:text published:boolean
bundle add administration-zero
rails db:migrate db:seed
rails generate admin:scaffold post title:string body:text published:boolean
bin/dev
```

However, unlike the README states, no `/admin` route is created, and if I visit http://localhost:3000/admin/posts, I get `uninitialized constant Admin::ApplicationController` thrown at the top of `Admin::PostsController`.

**Comment by lazaronixon** [comment]
Where is the rails generate admin:install ? This command is responsible to create the /admin route

**Comment by sedubois** [comment]
Sorry I did not see 🤦‍♂️ This works (I had to add ransack explictly):

```rb
rails new --javascript=esbuild demoapp && cd demoapp
rails generate model post title:string body:text published:boolean
bundle add administration-zero ransack
rails generate admin:install
rails db:migrate db:seed
rails generate admin:scaffold post title:string body:text published:boolean
bin/dev
```

After this I can log in at /admin. NB: the index page does not link to posts. I suppose the idea is that the user will then fix that himself.

![Screenshot 2022-03-11 at 10-52-15 Dashboard](https://user-images.githubusercontent.com/4217871/157843940-baa78c77-764d-45b0-9048-e873d0b04448.png)
