### ISSUE TITLE
Search feature?

### ISSUE THREAD

**Issue by sedubois** [lazaronixon/administration-zero#2]
Would it be possible to add a search functionality? The README links to Ransack, but no search box is visible in the screenshot. I [did not manage](https://github.com/lazaronixon/administration-zero/issues/1) to generate an app to have a look myself.

How would you compare this gem to [Administrate](https://github.com/thoughtbot/administrate)?

**Comment by lazaronixon** [comment]
You will see an example of how to use search in /admin/index.html.erb. This lib is no a engine, it’s only a generator for pure rails admin panels

**Comment by sedubois** [comment]
Okay after generating the app the proper way, I now see that the search filter works for Admin Users (the one generated for Posts is empty however).
